### ISSUE TITLE
Add `Unsupported Network` message and show warning icon

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#941] opened 2022-02-09 16:58 UTC
![Screenshot 2022-02-09 at 16 57 59](https://user-images.githubusercontent.com/25841025/153250677-2218e5b1-e590-4996-907e-a3f168d02fbc.png)

**Comment by irinelT** [comment] 2022-02-22 17:01
We are missing the message "Request to change network rejected by user".
Not sure if this message is necessary @Olafkuusik ?

**Comment by ShawTim** [comment] 2022-03-03 21:59
https://github.com/tempus-finance/tempus-app/issues/934
per this issue it looks like it's an expected behavior for not showing notifications when rejecting network changes.
https://github.com/tempus-finance/tempus-app/blob/a746d7e71755355d4350f8aadcb9eca5c5bdfb4c/packages/tempus-client_v2/src/components/navbar/ChainSelectorPopup.tsx#L49

**Comment by irinelT** [comment] 2022-03-04 19:43
The core issue is fixed.
Additional issues are addressed in #1072 .

![image](https://user-images.githubusercontent.com/98878781/156830994-5edc522b-fc32-4dcd-8d6a-19e253d75c82.png)

**Closed by irinelT** 2022-03-04 19:43 UTC
Labels: bug, low priority
