### ISSUE TITLE
Consider making whole row dark when row is hovered over

### ISSUE THREAD

**Issue by mijovic** [tempus-finance/tempus-app#259] opened 2021-09-28 08:59 UTC
Example:

<img width="1440" alt="Hover1" src="https://user-images.githubusercontent.com/23421619/135056767-746300e1-ee2d-4594-9314-a606c5f285ec.png">

<img width="1440" alt="Hover2" src="https://user-images.githubusercontent.com/23421619/135056821-1226197d-b2f2-4252-9c4d-3e07e63e1573.png">

**Comment by Olafkuusik** [comment] 2022-02-24 13:13
closing because it's duplicate of this issue: https://github.com/tempus-finance/tempus-app/issues/233

**Closed by Olafkuusik** 2022-02-24 13:13 UTC
Labels: ux
