### ISSUE TITLE
After deposit (variable yield) and return to dashboard, pool information does not update

### ISSUE THREAD

**Issue by davgarai** [tempus-finance/tempus-app#963] opened 2022-02-10 10:46 UTC
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/78982233/153391282-7d7bea1b-c889-4c80-b406-c5dc4524d499.png">
Refresh does not fix the issue

**Comment by irinelT** [comment] 2022-02-21 07:57
This issue is still reproducible. The dashboard is not updated until refresh.

**Comment by lazarmitic** [comment] 2022-02-21 08:46
Can you provide a list of values that are not being updated on the dashboard?

**Comment by irinelT** [comment] 2022-02-21 09:09
> Can you provide a list of values that are not being updated on the dashboard?

USDC

**Comment by lazarmitic** [comment] 2022-03-09 06:35
Balance update on dashboard after deposit fixed.

![balance-update-after-deposit-min](https://user-images.githubusercontent.com/7648077/157385799-325ff90d-aa6a-45de-850f-4e20a690de75.gif)

Available to deposit update needs some code refactoring that we planned to do in 2.2 so I suggest we move this issue to 2.2 as well since it's not a critical bug.

**Comment by irinelT** [comment] 2022-03-09 15:47
"Available to deposit" is not updated until the page is refreshed.

![image](https://user-images.githubusercontent.com/98878781/157477049-62e8f010-b07a-4275-8de7-8be38028bcd7.png)

**Comment by lazarmitic** [comment] 2022-03-09 15:53
Exactly, as I pointed out in my comment - I think we should fix this in 2.2 because it requires code refactor that we planned to have in 2.2, so instead of fixing it now, when we refactor some code and do a cleanup in 2.2 this will be fixed with it as well.

**Comment by lazarmitic** [comment] 2022-03-09 15:53
Can we open separate issue for Available to Deposit updates and put it in 2.2? :D

**Comment by irinelT** [comment] 2022-03-09 16:55
"Balance" is fixed.
"Available to deposit" will be fixed in #1147.

**Closed by irinelT** 2022-03-09 16:55 UTC
Labels: bug, ready for test
