### ISSUE TITLE
Transactions in "Transaction History" are not sorted properly

### ISSUE THREAD

**Issue by yuval-weiss** [tempus-finance/tempus-app#974] opened 2022-02-10 11:54 UTC
The top one should the the latest one

**Comment by RTP2016** [comment] 2022-02-10 11:57
Please can you attach the screenshot ser :)

**Comment by danieledamiani** [comment] 2022-02-10 12:11
![2](https://user-images.githubusercontent.com/25841025/153406255-0a1a24fb-3fce-4287-a48e-c821ec418a6e.png)

**Comment by danieledamiani** [comment] 2022-02-10 12:11
none of the other actions get picked up

**Comment by irinelT** [comment] 2022-02-17 15:26
Transaction history has many issues:

- It shows the USDT Withdrawal transation from my other accound, not from the une that is selected.
- It shows only last 5 transactions.
- The transaction dates are wrong **29 July 2022**.
- Sorting is strange, 24 then 29 then 24.

![image](https://user-images.githubusercontent.com/98878781/154512920-f10f692d-babe-408f-970f-ac8b21086435.png)

**Comment by danieledamiani** [comment] 2022-02-17 15:50
> Transaction history has many issues:
> 
> * It shows the USDT Withdrawal transaction from my other account, not from the one that is selected.
Can you please clarify?
> * It shows only last 5 transactions.
This is by design, it was decided to show only the last 5 transactions
> * The transaction dates are wrong **29 July 2022**.
These are the maturity dates of the pools
> * Sorting is strange, first is June, then July, then June.
See my answer above

**Comment by irinelT** [comment] 2022-02-22 15:01
The last transaction is shown on top of the history as requested, so this can be closed.
Other issues will be addressed in other tickets.

**Closed by irinelT** 2022-02-22 15:01 UTC
Labels: bug, ready for test, additional work
